name: 'deploy 2 nekoweb'
description: 'The definitive GitHub action for deploying your site to nekoweb!!!'

inputs:
  nekoweb-api-key:
    description: 'Your nekoweb API key.'
    required: true
  nekoweb-cookie:
    description: 'Your nekoweb cookie. (Required for Recently Updated feature)'
    required: false
  nekoweb-folder:
    description: 'The nekoweb folder to deploy to.'
    required: true
  directory:
    description: 'The directory you would like to deploy.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download deployment script
      run: |
        git clone --depth 1 https://github.com/deploy2nekoweb/deploy2nekoweb.git
      shell: bash

    - name: Setup bun
      uses: oven-sh/setup-bun@v2

    - run: |
        cd deploy2nekoweb
        if [ -n "${{ inputs.nekoweb-cookie }}" ]; then
          export NEKOWEB_COOKIE="${{ inputs.nekoweb-cookie }}"
        fi
        bun install
        cd ../
        bun run ./deploy2nekoweb/index.ts
      shell: bash
      env:
        NEKOWEB_API_KEY: ${{ inputs.nekoweb-api-key }}
        NEKOWEB_FOLDER: ${{ inputs.nekoweb-folder }}
        DIRECTORY: ${{ inputs.directory }}
